/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ButikKostume;

import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
/**
 *
 * @author Lenovo
 */
public class TambahKostum2 extends javax.swing.JFrame {

    /**
     * Creates new form TambahKostum
     */
    private DefaultTableModel model;
    private String filePath = "data.txt";

    public TambahKostum2() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        loadTableData();
    }

    private void loadTableData() {
        model.setRowCount(0);

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] data = line.split(",");
                model.addRow(data);
                
                // Mengubah format harga menjadi "Rp" tanpa tanda titik
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat membaca file", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     private void saveTableData() {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
            for (int i = 0; i < model.getRowCount(); i++) {
                StringBuilder line = new StringBuilder();
                for (int j = 0; j < model.getColumnCount(); j++) {
                    line.append(model.getValueAt(i, j));
                    if (j < model.getColumnCount() - 1) {
                        line.append(",");
                    }
                }
                writer.write(line.toString());
                writer.newLine();
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menulis ke file", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        konfirmasiPesanan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        DataPesanan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        tambahPesanan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BtnHapus = new javax.swing.JButton();
        checkOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(177, 232, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        konfirmasiPesanan.setBackground(new java.awt.Color(4, 163, 211));
        konfirmasiPesanan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        konfirmasiPesanan.setForeground(new java.awt.Color(255, 255, 255));
        konfirmasiPesanan.setText("KONFIRMASI PESANAN");
        konfirmasiPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiPesananActionPerformed(evt);
            }
        });
        jPanel1.add(konfirmasiPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 350, -1));

        jButton3.setBackground(new java.awt.Color(4, 163, 211));
        jButton3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("KEMBALI KE BERANDA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 350, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButikKostume/Tak berjudul178_20230606161513.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jPanel3.setBackground(new java.awt.Color(223, 179, 179));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 58, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(223, 179, 179));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("COSTUMER");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 370, 400));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButikKostume/Group 40 (1).png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 370, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kostum", "Harga", "Estimasi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 810, 180));

        DataPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kostum", "Harga", "Estimasi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(DataPesanan);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 810, 210));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel1.setText("Daftar Kostum");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("TOTAL HARGA");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, -1, 20));

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel5.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 270, 30));

        tambahPesanan.setBackground(new java.awt.Color(4, 163, 211));
        tambahPesanan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tambahPesanan.setForeground(new java.awt.Color(255, 255, 255));
        tambahPesanan.setText("TAMBAH PESANAN");
        tambahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPesananActionPerformed(evt);
            }
        });
        jPanel5.add(tambahPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 240, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel5.setText("Daftar Pesanan");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        BtnHapus.setBackground(new java.awt.Color(255, 102, 102));
        BtnHapus.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnHapus.setForeground(new java.awt.Color(255, 255, 255));
        BtnHapus.setText("HAPUS");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        jPanel5.add(BtnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 140, -1));

        checkOut.setBackground(new java.awt.Color(255, 255, 51));
        checkOut.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        checkOut.setText("CHECK OUT");
        checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutActionPerformed(evt);
            }
        });
        jPanel5.add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void konfirmasiPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasiPesananActionPerformed
     String email = JOptionPane.showInputDialog(this, "Masukkan email:");
     String alamat = JOptionPane.showInputDialog(this, "Masukkan alamat:");
        
        saveUserEmailAndAddress(email, alamat);
        
        DataPesanan a;
            a = new DataPesanan();
            a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_konfirmasiPesananActionPerformed
    
    private void saveUserEmailAndAddress(String email, String alamat) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("user_data.txt"))) {
            writer.write(email);
            writer.newLine();
            writer.write(alamat);
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menulis data pengguna", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tambahPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPesananActionPerformed
         // Mendapatkan baris yang dipilih dari jTable1
    int selectedRow = jTable1.getSelectedRow();
    
    // Memastikan baris yang dipilih valid
    if (selectedRow != -1) {
        // Mendapatkan data dari baris yang dipilih
        String kostum = jTable1.getValueAt(selectedRow, 0).toString();
        String harga = jTable1.getValueAt(selectedRow, 1).toString();
        // Mengubah format harga menjadi "Rp" tanpa tanda titik
    

        String estimasi = jTable1.getValueAt(selectedRow, 2).toString();
        
        // Menambahkan data ke DataPesanan (Tabel)
        DefaultTableModel dataPesananModel = (DefaultTableModel) DataPesanan.getModel();
        dataPesananModel.addRow(new Object[]{kostum, harga, estimasi});
        
        // Menyimpan data ke file
        saveTableData();
        
        // Menampilkan pesan berhasil
        JOptionPane.showMessageDialog(this, "Pesanan berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    } else {
        // Jika tidak ada baris yang dipilih, tampilkan pesan kesalahan
        JOptionPane.showMessageDialog(this, "Pilih salah satu kostum dari daftar", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_tambahPesananActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tampilanAwal a;
        a = new tampilanAwal();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
         // Mendapatkan baris yang dipilih dari DataPesanan (Tabel)
    int selectedRow = DataPesanan.getSelectedRow();

    // Memastikan baris yang dipilih valid
    if (selectedRow != -1) {
        // Konfirmasi penghapusan data
        int option = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus pesanan ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            // Menghapus baris yang dipilih dari DataPesanan (Tabel)
            DefaultTableModel dataPesananModel = (DefaultTableModel) DataPesanan.getModel();
            dataPesananModel.removeRow(selectedRow);

            // Menyimpan data ke file
            saveTableData();

            // Menampilkan pesan berhasil
            JOptionPane.showMessageDialog(this, "Pesanan berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        // Jika tidak ada baris yang dipilih, tampilkan pesan kesalahan
        JOptionPane.showMessageDialog(this, "Pilih salah satu pesanan dari daftar", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutActionPerformed
    int totalHarga = 0;
    DefaultTableModel dataPesananModel = (DefaultTableModel) DataPesanan.getModel();

    for (int i = 0; i < dataPesananModel.getRowCount(); i++) {
        int harga = Integer.parseInt(dataPesananModel.getValueAt(i, 1).toString());
        totalHarga += harga;
    }

    harga.setText(Integer.toString(totalHarga));
    }//GEN-LAST:event_checkOutActionPerformed

    
    
    private void populateTableFromFile(String filePath) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Hapus semua data yang ada di tabel
    model.setRowCount(0);

    try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] data = line.split(",");
            model.addRow(data);
        }
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat membaca file", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahKostum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahKostum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahKostum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahKostum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahKostum2().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHapus;
    private javax.swing.JTable DataPesanan;
    private javax.swing.JButton checkOut;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton konfirmasiPesanan;
    private javax.swing.JButton tambahPesanan;
    // End of variables declaration//GEN-END:variables
}
